// Generated by Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import Foundation;
@import CoreLocation;
@import CoreBluetooth;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSCoder;

SWIFT_CLASS("_TtC15MNNotifications8MNBeacon")
@interface MNBeacon : NSObject <NSCoding>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end

@class MNBeaconSignal;
@class MNVenue;
@class MNPOI;

SWIFT_CLASS("_TtC15MNNotifications22MNBeaconLocationSignal")
@interface MNBeaconLocationSignal : NSObject
@property (nonatomic, strong) MNBeaconSignal * _Nullable beacon;
@property (nonatomic, strong) MNVenue * _Nullable venue;
@property (nonatomic, copy) NSArray<MNPOI *> * _Nullable nearPOIs;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class MNProximity;

SWIFT_CLASS("_TtC15MNNotifications14MNBeaconSignal")
@interface MNBeaconSignal : NSObject
@property (nonatomic, copy) NSString * _Nullable uuid;
@property (nonatomic, copy) NSString * _Nullable regionId;
@property (nonatomic, strong) MNProximity * _Nullable proximity;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15MNNotifications12MNCustomVars")
@interface MNCustomVars : NSObject
@end

@class NSNumber;
enum MNEducation : NSInteger;
enum MNIncomeRange : NSInteger;
enum MNGender : NSInteger;
enum MNMaritalStatus : NSInteger;
enum MNEthnicity : NSInteger;

SWIFT_CLASS("_TtC15MNNotifications14MNDemographics")
@interface MNDemographics : NSObject <NSCoding>
@property (nonatomic, strong) NSNumber * _Nullable numberOfKids;
@property (nonatomic) enum MNEducation education;
@property (nonatomic) enum MNIncomeRange income;
@property (nonatomic) enum MNGender gender;
@property (nonatomic) enum MNMaritalStatus maritalStatus;
@property (nonatomic) enum MNEthnicity ethnicity;
@property (nonatomic, copy) NSString * _Nullable birthday;
@property (nonatomic, copy) NSString * _Nullable lang;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithNumberOfKids:(NSNumber * _Nullable)numberOfKids education:(enum MNEducation)education income:(enum MNIncomeRange)income gender:(enum MNGender)gender maritalStatus:(enum MNMaritalStatus)maritalStatus ethnicity:(enum MNEthnicity)ethnicity birthday:(NSString * _Nullable)birthday lang:(NSString * _Nullable)lang OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end

typedef SWIFT_ENUM(NSInteger, MNEducation) {
  MNEducationCOLLEGE = 0,
  MNEducationGRAD_SCHOOL = 1,
  MNEducationNON_COLLEGE = 2,
  MNEducationNOT_SET = 3,
};

typedef SWIFT_ENUM(NSInteger, MNEthnicity) {
  MNEthnicityASIAN = 0,
  MNEthnicityAFRICAN_AMERICAN = 1,
  MNEthnicityCAUSASIAN = 2,
  MNEthnicityHISPANIC = 3,
  MNEthnicityNOT_SET = 4,
};

typedef SWIFT_ENUM(NSInteger, MNGender) {
  MNGenderMALE = 0,
  MNGenderFEMALE = 1,
  MNGenderNOT_SET = 2,
};

typedef SWIFT_ENUM(NSInteger, MNIncomeRange) {
  MNIncomeRangeRANGE_$0_$30000 = 0,
  MNIncomeRangeRANGE_$30001_$60000 = 1,
  MNIncomeRangeRANGE_$60001_$100000 = 2,
  MNIncomeRangeRANGE_$100001_ = 3,
  MNIncomeRangeNOT_SET = 4,
};

@protocol MNNotificationsDelegate;
@class UILocalNotification;

SWIFT_CLASS("_TtC15MNNotifications9MNManager")
@interface MNManager : NSObject
+ (MNManager * _Nonnull)sharedInstance;
@property (nonatomic, strong) id <MNNotificationsDelegate> _Nullable delegate;
- (void)startSDK;
- (void)setDemographics:(MNDemographics * _Nonnull)demographics;
- (MNDemographics * _Nullable)getDemographics;
- (void)setCustomVars:(NSDictionary<NSString *, NSString *> * _Nonnull)customVars;
- (NSDictionary<NSString *, NSString *> * _Nullable)getCustomVars;
- (void)setTags:(NSArray<NSString *> * _Nonnull)tags;
- (NSArray<NSString *> * _Nullable)getTags;
- (void)disabledSDK;
- (void)enabledSDK;
- (void)processLocalNotification:(UILocalNotification * _Nonnull)notification;
- (BOOL)isMNNotification:(UILocalNotification * _Nonnull)notification;
- (void)blacklistBeaconUUIDs:(NSArray<NSString *> * _Nonnull)beaconUUIDs;
- (NSArray<NSString *> * _Nullable)getBeaconUUIDBlacklist;
@end

typedef SWIFT_ENUM(NSInteger, MNManagerErrorCodes) {
  MNManagerErrorCodesPLIST_ERROR = 0,
  MNManagerErrorCodesLOCATION_SERVICES_ERROR = 1,
  MNManagerErrorCodesDEEPLINK_ERROR = 2,
  MNManagerErrorCodesGENERIC_ERROR = 3,
};

typedef SWIFT_ENUM(NSInteger, MNMaritalStatus) {
  MNMaritalStatusMARRIED = 0,
  MNMaritalStatusSINGLE = 1,
  MNMaritalStatusNOT_SET = 2,
};

@class NSError;

SWIFT_PROTOCOL("_TtP15MNNotifications23MNNotificationsDelegate_")
@protocol MNNotificationsDelegate
@optional
- (void)mnManagerDidRangeBeacon:(MNBeaconLocationSignal * _Nonnull)beaconLocationSignal;
- (void)mnManagerDidChangeAuthorizationStatus:(CLAuthorizationStatus)status;
- (void)mnManagerDidChangeBluetoothState:(CBCentralManagerState)state;
- (void)mnManagerDidFailWithError:(NSError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC15MNNotifications5MNPOI")
@interface MNPOI : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15MNNotifications11MNProximity")
@interface MNProximity : NSObject <NSCoding>
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
@end


SWIFT_CLASS("_TtC15MNNotifications7MNVenue")
@interface MNVenue : NSObject
@property (nonatomic, copy) NSString * _Nullable id;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, copy) NSString * _Nullable type;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface UIDevice (SWIFT_EXTENSION(MNNotifications))
@end

#pragma clang diagnostic pop
