//
//  AppDelegate.m
//  MNNotificationsFunctionalDemoApp
//
//  Created by Jesus on 17/12/14.
//  Copyright (c) 2014 Mobiquity Networks. All rights reserved.
//

#import "AppDelegate.h"
#import "ViewController.h"

@interface AppDelegate ()

@end

@implementation AppDelegate


- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    return YES;
}

- (void)application:(UIApplication *)application didReceiveLocalNotification:(UILocalNotification *)notification
{
    // Notifications Manager SDK makes use of local notifications to show alerts to the user. Every local notification should be passed to -[MNNotificationsManager processLocalNotification:]
    ViewController *rootViewController = (ViewController *) self.window.rootViewController;
    if ([rootViewController.notificationsManager processLocalNotification:notification]) {
        NSLog(@"Notifications Manager has processed the local notification for us, it was a Notifications SDK generated local notification");
    } else {
        NSLog(@"Notifications Manager has not processed the local notification, we should do it here because it is a notification generated by our own app");
    }
}

- (void)applicationWillResignActive:(UIApplication *)application {
    
}

- (void)applicationDidEnterBackground:(UIApplication *)application {

}

- (void)applicationWillEnterForeground:(UIApplication *)application {

}

- (void)applicationDidBecomeActive:(UIApplication *)application {

}

- (void)applicationWillTerminate:(UIApplication *)application {

}

@end
